import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";

import RecoilContextProvider from "@/src/context/RecoilContextProvider";
import Nav from "../components/layout/Nav";
import Footer from "../components/layout/Footer";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.variable}>
        <RecoilContextProvider>
          <main className="bg-gray-900 ">
            <Nav />
            {children}
            <Footer />
          </main>
        </RecoilContextProvider>
      </body>
    </html>
  );
}
